# Generated by Django 2.2.10 on 2020-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0269_gitlab_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmfilter',
            name='stream_ids',
            field=models.TextField(default='u[]'),
        ),
    ]
