# Generated by Django 2.2.10 on 2020-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0271_auto_20200316_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmfilter',
            name='stream_ids',
            field=models.TextField(default=None),
        ),
    ]
